---
title: "Week-9-Code-Along+Challenge"
author: "Anandita Misra"
date: "2023-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#Slide-8- Tidy vs Non-Tidy Data


```{r cars}
library(tidyverse)
tidydata <- tribble(
~country,  ~year,  ~cases, ~population,
"Afghanistan",  1999,    745,   19987071,
"Afghanistan",  2000,   2666,   20595360,
"Brazil", 1999,  37737,  172006362,
"Brazil",  2000,  80488,  174504898,
"China", 1999, 212258, 1272915272,
"China",  2000, 213766, 1280428583)
tidydata


nontidydata <- tribble(
 ~country,~year,~rate,
"Afghanistan",  1999, "745/19987071",
"Afghanistan",  2000, "2666/20595360",
"Brazil", 1999, "37737/172006362",
"Brazil", 2000, "80488/174504898",
"China", 1999, "212258/1272915272",
"China", 2000, "213766/1280428583")
nontidydata
```

#Slide-11- Example-1 of Tidying Data

```{r}
nontidydata

tidieddata <- nontidydata %>%
  separate(rate, into = c("cases", 
                          "population"),
  sep = "/")
tidieddata

```

#Slide-12- Example-1 of Tidying Data Continued 

```{r}
newtidieddata <- tidieddata %>%
  pivot_longer(
    cols = cases:population,
    names_to = "measurement",
    values_to = "value"
  )
newtidieddata
```


#Slide-13- Example-1 of Tidying Data Continued 

```{r}
ggplot(newtidieddata) +
  aes(x=year,y=value, colour=country) +
  geom_point() +
  geom_line(aes(group = country))+
  facet_wrap(~measurement) +
  theme_bw()
```


#Slide-14- Example-2 of Tidying Data

```{r}
df <- tribble(
  ~id,  ~bp1, ~bp2,
   "A",  100,  120,
   "B",  140,  115,
   "C",  120,  125
) 
df

df %>%
  pivot_longer(
    cols = bp1:bp2,
    names_to = "measurement",
    values_to = "value"
)

```

#Slide-18- Example-3 of Reshaping Data

```{r}
newtidieddata

newtidieddata %>%
  pivot_wider(names_from="measurement",
              values_from="value")
```


#Slide-19- Example-4 of Reshaping Data

```{r}
df <- tribble(
  ~id, ~measurement, ~value,
  "A",        "bp1",    100,
  "B",        "bp1",    140,
  "B",        "bp2",    115,
  "A",        "bp2",    120,
  "A",        "bp3",    105
) 
df

df %>%
  pivot_wider(
    names_from = measurement,
    values_from = value
  )

```



#Challenge- First Part

```{r}
billboard

#Pivoting longer 

newbillboard<- billboard %>% pivot_longer(
cols = starts_with("wk"), 
names_to = "week", 
values_to = "rank"
) 
newbillboard

#Data Cleaning
newbillboard<- billboard %>% pivot_longer(
cols = starts_with("wk"), 
names_to = "week", 
values_to = "rank", 
values_drop_na = TRUE
) 

newbillboard 

#Column to have only numbers of the week
newbillboard <- newbillboard %>% mutate(week = parse_number(week))
newbillboard

#Plotting 
ggplot(newbillboard, aes(x = week, y = rank)) +
  geom_line()

```




#Challenge- Second Part

```{r}

cms_patient_experience

#Pivoting Wider
newcms_patient_experience <- cms_patient_experience %>%
  pivot_wider(names_from="measure_cd",
              values_from="prf_rate")
newcms_patient_experience

#Pivoting Wider
newcms_patient_experience <- cms_patient_experience %>%
  pivot_wider(names_from="measure_cd",
              values_from="prf_rate", 
              id_cols = starts_with("org")
              )
newcms_patient_experience
```